# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: How to install and connect to OwnCloud
email: lloyd.peterson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  -As an administrator, how do I install and configure an Owncloud server?
  -As an administrator, how do I enable users to connect to the Owncloud server using the server's IP address and port 8080?
  -As an administrator, how do I add a user account?
  -As a user, how do I connect to the Owncloud server using a desktop or mobile client?
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  whizzer75

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
